leftnav:
- identifier: 86a0cec7-c192-0c4b-bd1e-0c858f71ee63
  name: Syllabus
  url: /pages/syllabus
  weight: 10
- identifier: 7ace6332-aca0-4f1b-a7c7-7416c68b0958
  name: Calendar
  url: /pages/calendar
  weight: 20
- identifier: f119c4a4-4d80-6d78-f340-e61786952320
  name: Readings
  url: /pages/readings
  weight: 30
- identifier: 7c0429b6-dd42-da8d-013d-914b3036b33a
  name: Instructor Insights
  url: /pages/instructor-insights
  weight: 40
- identifier: 2ef9a3cc-0fcc-09de-bdab-80d890fad87d
  name: Lecture Slides
  url: /pages/lecture-slides
  weight: 50
- identifier: bb1b15e7-9a4f-89bd-a726-392698e4208c
  name: Video Lectures
  url: /pages/video-lectures
  weight: 60
- identifier: ffd3ae41-e2e5-258b-659e-16bc1fe96c0c
  name: Assignments
  url: /pages/assignments
  weight: 70
- identifier: 063483c8-ca5e-eab4-5744-84c18aaf4ae7
  name: Exams
  url: /pages/exams
  weight: 80
